version = 1

[[analyzers]]
name = "cfn-lint"
type = "community"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"